# Generated by Django 3.2.20 on 2026-01-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'التصنيف', 'verbose_name_plural': 'التصنيف'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'مهمة', 'verbose_name_plural': 'مهمة'},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'قيد العمل'), (2, 'مكتمل'), (3, 'مؤجل'), (4, 'ملغى')], default=1),
        ),
    ]
